development:
  adapter: postgresql
  database: storedom_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: storedom_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: storedom
  pool: 5
  timeout: 5000
